# Generated by Django 3.2.5 on 2021-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100)),
                ('customeremail', models.CharField(max_length=100)),
                ('customerphone', models.CharField(max_length=15)),
                ('cusername', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
                ('cconfirmpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
