# Generated by Django 3.2.5 on 2021-12-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0003_farmer_addproduct_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmer_addproduct_table',
        ),
    ]
