# Generated by Django 3.2.5 on 2021-12-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0005_farmer_productadding_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantname', models.CharField(max_length=100)),
                ('merchantemail', models.CharField(max_length=100)),
                ('merchantphone', models.CharField(max_length=15)),
                ('musername', models.CharField(max_length=100)),
                ('mpassword', models.CharField(max_length=100)),
                ('mconfirmpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
