# Generated by Django 3.2.5 on 2021-12-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_total', models.IntegerField()),
                ('order_status', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.cart')),
            ],
        ),
    ]
