# Generated by Django 3.2.5 on 2021-12-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0008_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('quantity', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('deliverydate', models.DateField(default='2020-02-09')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.cart')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.product_order')),
            ],
        ),
    ]
