# Generated by Django 3.2.5 on 2021-12-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0009_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productid',
        ),
        migrations.DeleteModel(
            name='farmer_signup_table',
        ),
        migrations.DeleteModel(
            name='merchant_signup_table',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='customer_signup_table',
        ),
        migrations.DeleteModel(
            name='farmer_productadding_table',
        ),
        migrations.DeleteModel(
            name='product_order',
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
