# Generated by Django 3.2.5 on 2021-12-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Crop_SS_App', '0010_auto_20211208_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100)),
                ('customeremail', models.CharField(max_length=100)),
                ('customerphone', models.CharField(max_length=15)),
                ('cusername', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
                ('cconfirmpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_productadding_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmername', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('Productcategory', models.CharField(max_length=100)),
                ('productimage', models.FileField(upload_to='media')),
                ('productprice_qty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmername', models.CharField(max_length=100)),
                ('farmerplace', models.CharField(max_length=100)),
                ('farmerphone', models.CharField(max_length=15)),
                ('fusername', models.CharField(max_length=100)),
                ('fpassword', models.CharField(max_length=100)),
                ('fconfirmpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='merchant_signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantname', models.CharField(max_length=100)),
                ('merchantemail', models.CharField(max_length=100)),
                ('merchantphone', models.CharField(max_length=15)),
                ('musername', models.CharField(max_length=100)),
                ('mpassword', models.CharField(max_length=100)),
                ('mconfirmpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_total', models.IntegerField()),
                ('order_status', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('quantity', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('deliverydate', models.DateField(default='2020-02-09')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.cart')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.product_order')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.customer_signup_table'),
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.farmer_productadding_table'),
        ),
    ]
