# Generated by Django 3.2.5 on 2021-12-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.merchant_signup_table')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crop_SS_App.farmer_productadding_table')),
            ],
        ),
    ]
