# Generated by Django 3.2.5 on 2021-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0016_pesticide_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_vegetbale_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantname', models.CharField(max_length=100)),
                ('merchantaddress', models.CharField(max_length=100)),
                ('vegname', models.CharField(max_length=100)),
                ('vegprice', models.CharField(max_length=100)),
                ('vegquantity', models.CharField(max_length=100)),
                ('farmername', models.CharField(max_length=100)),
            ],
        ),
    ]
