# Generated by Django 3.2.5 on 2021-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0017_merchant_vegetbale_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_fruit_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantname', models.CharField(max_length=100)),
                ('merchantaddress', models.CharField(max_length=100)),
                ('frutname', models.CharField(max_length=100)),
                ('frutprice', models.CharField(max_length=100)),
                ('frutquantity', models.CharField(max_length=100)),
                ('farmername', models.CharField(max_length=100)),
            ],
        ),
    ]
