# Generated by Django 3.2.5 on 2021-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0018_merchant_fruit_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_grain_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantname', models.CharField(max_length=100)),
                ('merchantaddress', models.CharField(max_length=100)),
                ('grname', models.CharField(max_length=100)),
                ('grprice', models.CharField(max_length=100)),
                ('grquantity', models.CharField(max_length=100)),
                ('farmername', models.CharField(max_length=100)),
            ],
        ),
    ]
