# Generated by Django 3.2.5 on 2021-12-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_SS_App', '0019_merchant_grain_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_plot_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmername', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('plotplace', models.CharField(max_length=100)),
                ('plotacres', models.CharField(max_length=100)),
            ],
        ),
    ]
